schema_version = "1.0.0"

id = "color_grid_generator"
name = "Color Grid Generator"
version = "1.1.0"
tagline = "Generate color grid textures for Unity and other game engines"
maintainer = "DevGOM"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["Material", "Paint"]
